name: sehatyuk
description: "Sehatyuk is a mobile application that allows users to make appointments with doctors."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.0
  file_picker: ^8.0.3
  flutter_launcher_icons: ^0.13.1
  mime: ^1.0.5
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  carousel_slider: ^4.2.1
  get: ^4.6.1 

flutter:
  uses-material-design: true
  assets:
    - assets/images/authenticationPage/
    - assets/images/detailDokterPage/
    - assets/images/profilePage/
    - assets/images/medReminderPage/
    - assets/images/pilihObatUntukPengingatPage/
    - assets/images/cariDokterPage/
    - assets/images/relasiPage/
    - assets/images/homePage/
    - assets/images/detailObatPage/
    - assets/images/daftarJanjiTemuPage/
    - assets/icon/backarrow.png
    - assets/images/CariObatPage/
    - assets/images/LoadPage/
    - assets/images/ambilAntrianPage/
  fonts:
    - family: Poppins
      fonts:
      - asset: fonts/Poppins/Poppins-Regular.ttf
      - asset: fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins/Poppins-Light.ttf
        weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LoadPage/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/LoadPage/Logo.png"
    background_color: "#fff"
    theme_color: "#fff"
  windows:
    generate: true
    image_path: "assets/images/LoadPage/Logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/LoadPage/Logo.png"